# Generated by Django 6.1 on 2026-09-04 10:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('github_repo_url', models.URLField(blank=True, default='')),
                ('live_demo_url', models.URLField(blank=True, default='')),
                ('synopsis_url', models.URLField(blank=True, default='')),
                ('ppt_url', models.URLField(blank=True, default='')),
                ('report_url', models.URLField(blank=True, default='')),
                ('research_paper_url', models.URLField(blank=True, default='')),
                ('media_urls', models.JSONField(default=list)),
                ('custom_deliverables', models.JSONField(default=dict)),
                ('github_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('synopsis_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('ppt_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('report_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('media_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('all_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='projects.studentgroup')),
            ],
            options={
                'db_table': 'project_submissions',
            },
        ),
    ]
