# Generated by Django 6.1 on 2026-10-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('SUPERVISOR', 'Supervisor'), ('HOD', 'HOD'), ('DEAN', 'Dean'), ('ADMIN', 'Admin')], max_length=20),
        ),
    ]
