# Generated by Django 6.1 on 2026-09-04 10:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('HOD', 'HOD Review'), ('DEAN', 'Dean Review')], max_length=10)),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=10)),
                ('comment', models.TextField()),
                ('actioned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'approval_records',
                'ordering': ['-actioned_at'],
            },
        ),
    ]
