/**
 * ARIS Curated Academic & Industry Domains and Technologies Dictionary
 * Formatted for autocomplete and skill tagging (similar to LinkedIn skills).
 */

export const DOMAINS_LIST: string[] = [
  // AI & Data Science
  'Artificial Intelligence & Machine Learning (AI/ML)',
  'Natural Language Processing (NLP)',
  'Computer Vision & Image Processing',
  'Deep Learning & Neural Networks',
  'Data Science & Predictive Analytics',
  'Big Data Engineering & Analytics',
  'Generative AI & LLM Systems',
  'Speech Recognition & Audio Processing',

  // Software & Systems Engineering
  'Full Stack Web Development',
  'Frontend Engineering',
  'Backend Engineering & Microservices',
  'Mobile Application Development (Android / iOS)',
  'Cross-Platform App Development',
  'Distributed Systems & Architecture',
  'Database Management & Optimization (DBMS)',
  'Software Testing & Quality Assurance (QA)',
  'Human-Computer Interaction (HCI) & UI/UX',

  // Cloud & Infrastructure
  'Cloud Computing & Virtualization',
  'DevOps & Continuous Integration / Continuous Deployment (CI/CD)',
  'Site Reliability Engineering (SRE)',
  'Serverless Computing & Cloud Native Architecture',

  // Security & Networks
  'Cybersecurity & Ethical Hacking',
  'Network Security & Cryptography',
  'Application Security & Penetration Testing',
  'Information Security & Cyber Defense',

  // Hardware, Embedded & Emerging Tech
  'Internet of Things (IoT) & Smart Systems',
  'Embedded Systems & Firmware Development',
  'Robotics & Autonomous Systems',
  'Blockchain & Distributed Ledger Technology (DLT)',
  'Augmented Reality & Virtual Reality (AR/VR / XR)',
  'Quantum Computing & Quantum Algorithms',
  'Edge & Fog Computing',
  'Bioinformatics & Computational Biology',
  'Geographic Information Systems (GIS) & Remote Sensing',
  'Game Design & Interactive Media',
  'High Performance Computing (HPC)',
];

export const TECHNOLOGIES_LIST: string[] = [
  // Programming Languages
  'Python',
  'JavaScript',
  'TypeScript',
  'Java',
  'C',
  'C++',
  'C# (.NET)',
  'Go (Golang)',
  'Rust',
  'PHP',
  'Kotlin',
  'Swift',
  'Dart',
  'R',
  'SQL',
  'Shell / Bash Scripting',
  'Solidity',
  'MATLAB',
  'Scala',

  // Web Frameworks & Frontend
  'React.js',
  'Next.js',
  'Vue.js',
  'Nuxt.js',
  'Angular',
  'Svelte',
  'SvelteKit',
  'HTML5 / CSS3',
  'Tailwind CSS',
  'Bootstrap',
  'Material UI (MUI)',
  'Chakra UI',
  'Shadcn UI',
  'Redux / Redux Toolkit',
  'Zustand',
  'GraphQL',
  'Apollo Client',
  'RESTful APIs',
  'WebSockets / Socket.io',

  // Backend Frameworks & Runtimes
  'Node.js',
  'Express.js',
  'NestJS',
  'Django',
  'Django REST Framework (DRF)',
  'FastAPI',
  'Flask',
  'Spring Boot',
  'ASP.NET Core',
  'Laravel',
  'Ruby on Rails',
  'Fastify',
  'gRPC',

  // Mobile Frameworks
  'React Native',
  'Flutter',
  'Android SDK',
  'SwiftUI / iOS',
  'Jetpack Compose',
  'Expo',
  'Capacitor / Ionic',

  // Databases & Storage
  'PostgreSQL',
  'MySQL',
  'SQLite',
  'MongoDB',
  'Redis',
  'Supabase',
  'Firebase Firestore',
  'Firebase Realtime Database',
  'Apache Cassandra',
  'Amazon DynamoDB',
  'Neo4j (Graph DB)',
  'Elasticsearch',
  'Prisma ORM',
  'Drizzle ORM',
  'SQLAlchemy',

  // Cloud & DevOps
  'Amazon Web Services (AWS)',
  'Microsoft Azure',
  'Google Cloud Platform (GCP)',
  'Docker',
  'Docker Compose',
  'Kubernetes (K8s)',
  'GitHub Actions',
  'GitLab CI/CD',
  'Jenkins',
  'Terraform',
  'Nginx',
  'Linux / Ubuntu Server',
  'Vercel',
  'Netlify',
  'Cloudflare',
  'Prometheus & Grafana',

  // AI, Machine Learning & Data Science
  'PyTorch',
  'TensorFlow',
  'Keras',
  'Scikit-learn',
  'OpenCV',
  'Hugging Face Transformers',
  'LangChain',
  'LlamaIndex',
  'Ollama',
  'Pandas',
  'NumPy',
  'SciPy',
  'Matplotlib / Seaborn',
  'Apache Spark',
  'Apache Kafka',
  'Jupyter Notebooks',
  'YOLO (Object Detection)',
  'MediaPipe',

  // Security, Testing & Tools
  'Git & GitHub',
  'Postman',
  'Wireshark',
  'Burp Suite',
  'Metasploit',
  'Kali Linux',
  'Nmap',
  'Jest',
  'Cypress',
  'Selenium',
  'Playwright',
  'Vite',
  'Webpack',
];
