# Generated by Django 6.1 on 2026-09-04 10:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectIdea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('problem_statement', models.TextField()),
                ('novelty', models.TextField()),
                ('domain', models.CharField(max_length=100)),
                ('technologies', models.JSONField(default=list)),
                ('is_taken', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_ideas', to='accounts.supervisorprofile')),
            ],
            options={
                'db_table': 'project_ideas',
            },
        ),
        migrations.CreateModel(
            name='ProjectTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('MINOR_1', 'Minor Project I'), ('MINOR_2', 'Minor Project II'), ('MAJOR', 'Major Project'), ('RESEARCH', 'Research Paper'), ('HARDWARE', 'Hardware / IoT Project'), ('INNOVATION', 'Innovation / Capstone')], default='MINOR_1', max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('target_program', models.CharField(max_length=50)),
                ('target_semester', models.PositiveSmallIntegerField()),
                ('is_mandatory', models.BooleanField(default=True)),
                ('max_group_size', models.PositiveSmallIntegerField(default=3)),
                ('required_deliverables', models.JSONField(default=list)),
                ('min_media_files', models.PositiveSmallIntegerField(default=5)),
                ('max_media_files', models.PositiveSmallIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tracks', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tracks', to='accounts.academicsession')),
            ],
            options={
                'db_table': 'project_tracks',
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('FORMED', 'Group Formed'), ('SUPERVISOR_PENDING', 'Supervisor Pending'), ('PROPOSAL_PENDING', 'Proposal Under Review'), ('PROPOSAL_REJECTED', 'Proposal Rejected'), ('ACTIVE', 'Project Active (Approved)'), ('SUBMITTED', 'Deliverables Submitted'), ('HOD_APPROVED', 'HOD Approved'), ('DEAN_APPROVED', 'Dean Approved (Archived)')], default='FORMED', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_groups', to='accounts.supervisorprofile')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='projects.projecttrack')),
            ],
            options={
                'db_table': 'student_groups',
            },
        ),
        migrations.CreateModel(
            name='ProjectProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposal_type', models.CharField(choices=[('FROM_LIST', 'From Supervisor Idea Pool'), ('OWN_IDEA', 'Own Custom Project Idea')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('problem_statement', models.TextField()),
                ('novelty', models.TextField()),
                ('domain', models.CharField(max_length=100)),
                ('technologies', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('supervisor_feedback', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_idea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='projects.projectidea')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='projects.studentgroup')),
            ],
            options={
                'db_table': 'project_proposals',
                'ordering': ['-version'],
            },
        ),
        migrations.AddField(
            model_name='projectidea',
            name='taken_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_idea', to='projects.studentgroup'),
        ),
        migrations.CreateModel(
            name='ProjectDeadline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deadline_type', models.CharField(choices=[('SYNOPSIS', 'Synopsis Submission'), ('PPT', 'Presentation Submission'), ('REPORT', 'Final Report Submission'), ('GITHUB', 'GitHub Repository Link'), ('CUSTOM', 'Custom Milestone')], max_length=15)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('due_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('set_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deadlines_set', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='projects.projecttrack')),
            ],
            options={
                'db_table': 'project_deadlines',
                'unique_together': {('track', 'deadline_type')},
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_role', models.CharField(choices=[('LEADER', 'Team Leader'), ('MEMBER', 'Member')], default='MEMBER', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='accounts.studentprofile')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.studentgroup')),
            ],
            options={
                'db_table': 'group_members',
                'unique_together': {('group', 'student')},
            },
        ),
    ]
