# Generated by Django 6.1 on 2026-09-05 08:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttrack',
            name='coordinator',
            field=models.ForeignKey(blank=True, help_text='Faculty member assigned by HOD to coordinate track lab sessions & presentations.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_tracks', to='accounts.supervisorprofile'),
        ),
        migrations.CreateModel(
            name='ProjectSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('session_type', models.CharField(choices=[('WEEKLY_LAB', 'Weekly Progress Lab'), ('SYNOPSIS_PPT', 'Synopsis Physical Presentation'), ('MID_TERM_PPT', 'Mid-Term Progress Review'), ('FINAL_PPT', 'Final Classroom PPT Presentation'), ('DOUBT_SOLVE', 'Guidance & Doubt Session')], default='WEEKLY_LAB', max_length=20)),
                ('target_section', models.CharField(blank=True, default='ALL', help_text='e.g. A, B, C or ALL', max_length=5)),
                ('scheduled_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('venue', models.CharField(help_text='e.g. Lab 3, Ground Floor CSE Block, Room 204', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_sessions', to='accounts.supervisorprofile')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='projects.projecttrack')),
            ],
            options={
                'db_table': 'project_sessions',
                'ordering': ['scheduled_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late')], default='PRESENT', max_length=10)),
                ('progress_notes', models.TextField(blank=True, default='', help_text='Coordinator feedback from classroom presentation')),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_attendances', to='projects.studentgroup')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='projects.projectsession')),
            ],
            options={
                'db_table': 'session_attendances',
                'unique_together': {('session', 'group')},
            },
        ),
    ]
