# Generated by Django 6.1 on 2026-09-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projecttrack_coordinator_projectsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdeadline',
            name='instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projectdeadline',
            name='late_submission_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectdeadline',
            name='template_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='projectdeadline',
            name='template_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='projectidea',
            name='supporting_doc_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='projectidea',
            name='supporting_doc_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
