# Generated by Django 6.1 on 2026-10-02 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailotpverification'),
        ('projects', '0003_projectdeadline_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectproposal',
            name='solution',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals_received', to='accounts.supervisorprofile'),
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='supporting_doc_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='supporting_doc_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
