# Generated by Django 6.1 on 2026-10-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_groupjoinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttrack',
            name='max_groups_per_supervisor',
            field=models.PositiveSmallIntegerField(default=3, help_text='Maximum groups a supervisor can mentor in this track (set by HOD).'),
        ),
    ]
