# Generated by Django 6.1 on 2026-10-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projecttrack_max_groups_per_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdeadline',
            name='file_format',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdeadline',
            name='font_family',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdeadline',
            name='page_limit',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdeadline',
            name='page_margins',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='projectdeadline',
            name='spacing_alignment',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='projectdeadline',
            name='typography',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
