# Generated by Django 6.1 on 2026-09-05 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorprofile',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending HOD Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_supervisors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
