# Generated by Django 6.1 on 2026-09-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_supervisorprofile_approval_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp_code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'email_otp_verifications',
                'indexes': [models.Index(fields=['email', '-created_at'], name='email_otp_v_email_7e20a0_idx')],
            },
        ),
    ]
