# Generated by Django 6.1 on 2026-10-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_school_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorprofile',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending Administrator Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
