# Generated by Django 6.1 on 2026-09-04 10:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('PROPOSAL_SUBMITTED', 'Proposal Submitted'), ('PROPOSAL_APPROVED', 'Proposal Approved'), ('PROPOSAL_REJECTED', 'Proposal Rejected'), ('SUBMISSION_DUE', 'Submission Due Soon'), ('SUBMISSION_DONE', 'Deliverables Submitted'), ('HOD_APPROVED', 'HOD Approved'), ('HOD_REJECTED', 'HOD Rejected'), ('DEAN_APPROVED', 'Dean Approved')], max_length=25)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('target_url', models.CharField(blank=True, default='', max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
